### ISSUE TITLE
Error while compile

### ISSUE THREAD

**Issue by ghost** [Dirli/budgie-cpufreq-applet#2]
Hi there, i tried to install it but receive this error:

 christoph3   master  ~  TEMP  budgie-cpufreq-applet  meson build --prefix /usr --buildtype=plain
The Meson build system
Version: 0.49.2
Source dir: /home/christoph3/TEMP/budgie-cpufreq-applet
Build dir: /home/christoph3/TEMP/budgie-cpufreq-applet/build
Build type: native build
Project name: budgie-cpufreq-applet
Project version: 1.0.1
Native C compiler: cc (gcc 8.2.0 "cc (Solus) 8.2.0")

meson.build:1:0: ERROR:  Could not execute Vala compiler "valac"

A full log can be found at /home/christoph3/TEMP/budgie-cpufreq-applet/build/meson-logs/meson-log.txt

**Comment by Dirli** [comment]
You have not specified which OS you have. It doesn't matter here though. Install vala on your system.
